"""Added table

Revision ID: 094e39740d7e
Revises: 42063c093f80
Create Date: 2024-11-12 16:55:58.685518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094e39740d7e'
down_revision: Union[str, None] = '42063c093f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_twitter_data')
    op.drop_table('raw_twitter_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_twitter_data',
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_created', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_followers', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_friends', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_favourites', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_verified', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_retweet', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('processed_twitter_data',
    sa.Column('user_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_created', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_followers', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_friends', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_favourites', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_verified', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashtags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_retweet', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
